apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: kube-event-tail-reader-binding
subjects:
    - kind: ServiceAccount
      name: kube-event-tail
      namespace: kube-system
roleRef:
    kind: ClusterRole
    name: kube-event-tail-reader
    apiGroup: rbac.authorization.k8s.io
