resources:
    - name: source
      type: git
      icon: github-circle
      source:
          uri: https://github.com/jrockway/kube-event-tail
    - name: golang-latest
      type: registry-image
      icon: docker
      source:
          repository: golang
          tag: latest
    - name: kube-event-tail-version
      type: semver
      icon: counter
      source:
          driver: s3
          bucket: ((versions.bucket))
          access_key_id: ((versions.access_key_id))
          secret_access_key: ((versions.secret_access_key))
          region_name: ((versions.region_name))
          endpoint: ((versions.endpoint))
          key: kube-event-tail-version
          initial_version: 0.0.1
    - name: kube-event-tail-container
      type: registry-image
      icon: docker
      source:
          repository: registry.jrock.us/kube-event-tail
          username: ((registry.username))
          password: ((registry.password))

jobs:
    - name: build
      public: true
      plan:
          - get: golang-latest
            trigger: true
          - get: source
            trigger: true
          - task: test
            image: golang-latest
            config:
                platform: linux
                inputs:
                    - name: source
                      path: kube-event-tail
                run:
                    path: /bin/sh
                    args:
                        - -c
                        - |
                            cd kube-event-tail
                            go test -v -race ./...
          - get: kube-event-tail-version
            params:
                bump: patch
          - task: build
            privileged: true
            config:
                platform: linux
                image_resource:
                    type: registry-image
                    source:
                        repository: vito/oci-build-task
                params:
                    CONTEXT: source
                inputs:
                    - name: source
                outputs:
                    - name: image
                run:
                    path: build
          - put: kube-event-tail-container
            params:
                image: image/image.tar
                additional_tags: kube-event-tail-version/version
          - put: kube-event-tail-version
            params:
                file: kube-event-tail-version/version
